spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weixin?serverTimezone=UTC&characterEncoding=UTF-8&&allowMultiQueries=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
#必须开启标签多SQL事务
server:
  port: 8081

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml

