spring:
  datasource:
    url: jdbc:mysql://124.70.221.15:3306/weixin?serverTimezone=UTC&characterEncoding=UTF-8&&allowMultiQueries=true
    username: weixin
    password: Tsc20010401
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
#必须开启标签多SQL事务
server:
  port: 8081

# token持续时间
token-time:
  short: 300
  long: 400

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml

